name: Depravare
favicon: null
layout_spectrum: 0.41269
typography_spectrum: 0.15436679497361183
title: "Depravare's Stream's Website!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#f0fbf7'
    - '#54473a'
    - '#96795e'
    - '#8fccdf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
